<a href="https://colab.research.google.com/github/JeongGiyoung/Learning/blob/main/python_%EC%A0%95%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# python syntax
  * (컴퓨터 언어의) 문법

# # 용어 정리

## ## IDE :
  * Integrated Development Environment
  * 공통된 개발자 툴을 하나의 그래픽 사용자 인터페이스(Graphical User Interface, GUI)로 결합하는 애플리케이션을 구축하기 위한 소프트웨어
  * 구성요소
    - 소스 코드 편집기
    - 로컬 빌드 자동화
    - 디버거

# # Colab

## ## 이미지 불러오기

In [ ]:
from IPython.display import Image

#미로게임_학습사이클.jpg
Image('/content/drive/MyDrive/Colab Notebooks/딥러닝/res/rl/미로게임_학습사이클.jpg')

# # 기초 명령문

## ## 현재 작업 환경(디렉토리 확인)

In [ ]:
# !명령어
# 현재 작업 환경(디렉토리 확인)
!ls

sample_data


## ## 파이썬의 버전 확인

In [ ]:
# 현재 개발 환경에서 파이썬의 버전 확인
!python -V

Python 3.7.13


## ## 파이썬 패키지 확인

In [ ]:
# 현재 개발 환경에서 기본 섪치 되어 있는 파이썬 패키지 확인
# 내가 뭔가를 개발할려고 하는데 별도의 패키지(남이 만든것)을 사용해야 한다
# 그것이 현재 환경에 존재하는가? 체크
# 존재한다면 내가 쓰고 싶은 버전과 일치하는가? 혹은 호환되는가? 체크
!pip list

Package                       Version
----------------------------- ---------------------
absl-py                       1.0.0
alabaster                     0.7.12
albumentations                0.1.12
altair                        4.2.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arviz                         0.12.0
astor                         0.8.1
astropy                       4.3.1
astunparse                    1.6.3
atari-py                      0.2.9
atomicwrites                  1.4.0
attrs                         21.4.0
audioread                     2.1.9
autograd                      1.4
Babel                         2.9.1
backcall                      0.2.0
beautifulsoup4                4.6.3
bleach                        5.0.0
blis                          0.4.1
bokeh                         2.3.3
Bottleneck                    1.3.4
branca                        0.5.0
bs4                           0.0.1
CacheC

# # 기본 연산자

## ## 나누기할 때 몫 값만 출력

In [ ]:
print(5 // 3)

1


## ## 나누기할 때 몫을 빼고 나머지 값만 출력

In [ ]:
print(5 % 3) 

2


## ## ** : 제곱 출력

In [ ]:
print(2 ** 10) 

1024


## ## int() : 정수 값으로 출력

In [ ]:
print(int(5 / 3)) 
print(int('10'))

1
10


## # float() : 실수 표현

In [ ]:
print(float(5))

5.0


## # type() : 형식 확인

In [ ]:
print(type(10))
print(type(10.0))

<class 'int'>
<class 'float'>


## # 루트 계산

In [ ]:
import math
print(math.sqrt(3))

1.7320508075688772


## # 빈 리스트 생성

In [ ]:
arr4 = list()

## # 튜플
### * tuple()은 수정 불가능

In [ ]:
tuple1 = (1,2,3,4,5)
print(tuple1)

tup1 = tuple(range(1,6))

#tup1[0] = 99
print(tup1)

(1, 2, 3, 4, 5)
(1, 2, 3, 4, 5)


## ## range()

In [ ]:
arr = list(range(1,6))
arr1 = list(range(6))
arr, arr1

([1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5])

## # range(... , ... , **) 증가량 수정

In [ ]:
arr = list(range(2, 101, 2))
arr

## # .sort() : 오름차순

In [ ]:
arr4.sort()

## # .reverse() : 내림차순

In [ ]:
arr4.reverse()

## # {... : ...} : (딕션너리) 키, 값을 지정. 

In [ ]:
dic1 = {1 : 'a'}

dic1[2] = 'b'

print(dic1)

{1: 'a', 2: 'b'}


## # 문자열 연산

In [ ]:
stat1 = 'Hello'
stat2 = 'World'
res = stat1 + stat2
print(res)

HelloWorld


## # 문자열 연산에는 +, * 만 있음
### * 문자열에는 빼기, 나누기가 없음
### * 문자열끼리 곱하기 없음

In [ ]:
print(stat1 + stat2)

print(stat1 * 5)

HelloWorld
HelloHelloHelloHelloHello


## # 문자열 길이
  * len()

## # 변수[-1] : 뒤에서 첫번째 문자

In [ ]:
stat3 = stat1 + stat2

print(stat3[-1])

d


## # 변수[0:?] : 문자열 자르기

In [ ]:
일시 = '2022-01-17 14:39:25'

# 시작은 '0'을 생략해도 된다

print(일시[:4],'년') 
print(일시[5:7],'월')
print(일시[8:10],'일')
print(일시[11:13],'시')
print(일시[14:16],'분')

# 끝은 마지막 번호를 생략해도 된다

print(일시[17:],'초') 

print(일시[-5:-3], '분')

2022 년
01 월
17 일
14 시
39 분
25 초
39 분


## ## +=
  * 왼쪽 변수에 오른쪽 값을 더한 후, 그 결과를 왼쪽 변수에 할당

In [ ]:
num1 = 10
num2 = 2
num1 += num2

print(num1)

12


# 연속 데이터 타입

- 단일 데이터 n개를 가지고 있는 자료구조
- 연속형, 시퀀스형 표현
- 튜플만 수정불가

|타입명|기호|특징|크기|
|--|--|--|--|
|리스트|[]|- list()<br>- []<br>- 순서(인덱스) O<br>- 값 중복 O|len()|
|딕셔너리|{}|- dict()<br>- {}<br>- 순서(인덱스) X<br>- 값 중복 O, 키 중복 X<br>- 키와 값의 세트로 구성<br>- 타언어와 통신시 json으로 대응됨 |len()|
|튜플|()|- tuple()<br>- ()<br>- 순서(인덱스) O<br>- 값 중복 O<br>- 단수하게 값을 묶는다|len()|
|집합|{}|- set()<br>- {}<br>- 순서(인덱스) X<br>- 값 중복 X<br>- 중복제거|len()|
|배열|ndarray|-numpy의 자료구조, 행렬|shape|
|시리즈|Series|-pandas의 자료구조, 1차원 구조|shape|
|데이터프레임|DataFrame|-pandas의 자료구조, 2차원 구조|shape|
|텐서|Tensor|-딥러닝중요 엔진들의 자료구조, tensorflow, pytorch|shape|

## ## list('문자열')
  * 문자열을 list에 넣으면 자동으로 한 글자씩 나눈다.

In [ ]:
tmp = list('abc')
tmp

['a', 'b', 'c']

# # numpy

## ## zeros(3)
  * 3개의 0을 요소로서 가지는 1차원 array를 생성하라는 의미
    - 빈 공간을 만들되, shape을 맞출 필요가 있을 때 

In [ ]:
import numpy as np


arr_test = np.zeros(3)
print(arr_test)

[0. 0. 0.]


## ## zeros_like()

## ## np.random.randint()

In [ ]:
 a = np.random.randint(6)
 a

4

## ## numpy.argmax()
  * 주어진 NumPy 배열에서 가장 높은 값을 가진 값의 인덱스를 반환

In [ ]:
import numpy as np

a=np.array([2,6,1,5])

print("Array:")
print(a)

req_index=np.argmax(a)
print("\nIndex with the largest value:")
print(req_index)

print("\nThe largest value in the array:")
print(a[req_index])

Array:
[2 6 1 5]

Index with the largest value:
1

The largest value in the array:
6


# 포맷팅(formatting)

## # {}.fromat(문자) : 문자열 포맷팅

In [ ]:
str1 = "I'm so happy {} U".format(2)
str1 = "I'm so happy {} U".format('to')
print(str1)

I'm so happy to U


In [ ]:
str1 = "I'm so happy {} U. are {}?".format('to', 'You')

첫번째 = '투'
두번째 = '유'

str1 = "I'm so happy {} U. are {}?".format(첫번째, 두번째)
print(str1)

I'm so happy 투 U. are 유?


## # f"...{}..." : 문자열 포맷팅 생략형

In [ ]:
str2 = f"I'm so happy {첫번째} U. are {두번째}?"
print(str2)

I'm so happy 투 U. are 유?


## # format(... , ',d') : 천단위 마다 쉼표 출력

In [ ]:
money = 100000000000000000000
print(format(money, ',d'))

100,000,000,000,000,000,000


# 날짜

## # 현재 일시

In [ ]:
from datetime import datetime

now = datetime.now() 

print(now)

2022-04-29 08:55:51.256742


## # strftime(...) : 양식

In [ ]:
print(now.strftime('%Y년 %m월 %d일 %H:%M:%S'))

2022년 04월 29일 08:55:51


# 문자열 조정 함수

## # split() : 분할

In [ ]:
# 띄어쓰기 기준으로 분할

full_name = 'Hugo MG Sung'

full_name.split()

['Hugo', 'MG', 'Sung']

In [ ]:
# split(',') : 쉼표기준으로 분할

test = 'Hey, guys'

test.split(',')

['Hey', ' guys']

## # .replace() : 단어교체

In [ ]:
full_name = 'Hugo MG Sung'

full_name.replace('Hugo MG', 'Ashely')

'Ashely Sung'

## # 공백 삭제

In [ ]:
# .strip() : 공백 삭제 / Oracle 에서 trim 명령어와 동일
## .lstrip() : 왼쪽 공백 삭제
### .rstirp() : 오른쪽 공백 삭제

aaa = '      Hello, World     '

aaa.rstrip()

'      Hello, World'

## # 문자열이 자리한 위치를 숫자로 출력

In [ ]:
full_name = 'Hugo MG Sung'

print(full_name.index('H'))
print(full_name.index('u'))
print(full_name.index('g')) 
print(full_name.index('G'))

0
1
2
6


## # 문자열이 자리한 위치를 숫자로 출력

In [ ]:
full_name = 'Hugo MG Sung'

print(full_name.find('X'))
print(full_name.find('MG'))

-1
5


## # 찾는 문자의 개수

In [ ]:
full_name = 'Hugo MG Sung'

print(full_name.count('u'))
print(full_name.count('n'))

2
1


## # 문자열의 각 문자마다 합칠 때 다른 문자를 넣으면서 합칠 때

In [ ]:
full_name = 'Hugo MG Sung'

'-'.join(full_name)

'H-u-g-o- -M-G- -S-u-n-g'

## # 대문자 소문자

In [ ]:
full_name = 'Hugo MG Sung'

print(full_name.upper())
print(full_name.lower())

HUGO MG SUNG
hugo mg sung


## ## strip

In [ ]:
# 12. 공백제거
tmp = '''
				
					
					
					
					유럽연합 EUR
				
'''
# 문자열의 앞뒤 공백 제거 -> 문자열 함수 사용
f'[{tmp.strip()}]', f'[{tmp.lstrip()}]', f'[{tmp.rstrip()}]'

('[유럽연합 EUR]',
 '[유럽연합 EUR\n\t\t\t\t\n]',
 '[\n\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t유럽연합 EUR]')

## ## [%s] %

In [ ]:
# 14. 문자열 포멧팅 응용에서 값의 자리수(칸수) 지정
'[%s]' % 'abcd'

'[abcd]'

In [ ]:
# 10칸을 무조건 차지한다
'[%10s]' % 'abcd', '[%-10s]' % 'abcd'

('[      abcd]', '[abcd      ]')

## ## '[%10f]' %

In [ ]:
'[%10f]' % 3.145678, '[%10s]' % 3.145678

('[  3.145678]', '[  3.145678]')

## ## '[%10.2f]' %
  * 소수점 자리수 정하기

In [ ]:
'[%10.2f]' % 3.145678

'[      3.15]'

In [ ]:
'[{:10}]'.format('abcd')
# '[{0:-10}]'.format('abcd') : 에러 발생

'[abcd      ]'

## ## '[{:<10}]'.format()
  * 좌우 정렬

In [ ]:
# 앞쪽, 뒤쪽으로 정렬
'[{0:<10}]'.format('abcd'), '[{0:>10}]'.format('abcd')

('[abcd      ]', '[      abcd]')

## ## '[{0:^10}]'.format()
  * 중앙정렬

In [ ]:
# 중심
'[{0:^10}]'.format('abcd'), '[{0:*^10}]'.format('abcd')

('[   abcd   ]', '[***abcd***]')

In [ ]:
a = 'abcd'
f'[{a:10}]', f'[{a:>10}]', f'[{a:^10}]'

('[abcd      ]', '[      abcd]', '[   abcd   ]')

# if

In [ ]:
name = ['명건', '태경', '기영', '광조']

if '길동' in name :
    print('의사쌤한테 인사합니다.')
    
elif name == '다원' :
    print('주사실로 갑니다.')

else : 
    print('호출할 때까지 대기합니다.')

호출할 때까지 대기합니다.


  * 중첩 if

In [ ]:
x = 11

if x > 0 : 
    print('양수')
    
    if x > 9 :
        print('10보다 큰 수')
        
    else :
        print('10보다 작은 수')
        
elif x == 0 :
    print('0')
    
else :
    print('음수')

양수
10보다 큰 수


## # 할당 연산자

  * 왼쪽 변수에 오른쪽 값을 할당한다
    - c = a + b → c = a + b
    
  * 왼쪽 변수에 오른쪽 값을 더하고 결과를 왼쪽변수에 할당
    - c += a → c = c + a
    
  * 왼쪽 변수에서 오른쪽 값을 빼고 결과를 왼쪽변수에 할당
    - c -= a → c = c - a

  * 왼쪽 변수에 오른쪽 값을 곱하고 결과를 왼쪽변수에 할당
    - c *= a → c = c * a
  
  * 왼쪽 변수에서 오른쪽 값을 나누고 결과를 왼쪽변수에 할당
    - c /= a → c = c / a
  
  * 왼쪽 변수에서 오른쪽 값을 나눈 나머지의 결과를 왼쪽변수에 할당
    - c %= a → c = c % a
    
  * 왼쪽 변수에 오른쪽 값만큼 제곱을 하고 결과를 왼쪽변수에 할당
    - c **= a → c = c ** a
    
  * 왼쪽 변수에서 오른쪽 값을 나눈 몫의 결과를 왼쪽변수에 할당
    - c //= a → c = c // a

In [ ]:
numbers = list(range(1, 21))

res = 0

for item in numbers :
    res += item

print(f'{ numbers[-1] } 까지의 총 합은 {res} 입니다.')

20 까지의 총 합은 210 입니다.


## # 짝수 표현

In [ ]:
numbers = list(range(1, 21))

for item in numbers :
    
    if item % 2 == 0 :
        
        print(f'{item}은 짝수')

2은 짝수
4은 짝수
6은 짝수
8은 짝수
10은 짝수
12은 짝수
14은 짝수
16은 짝수
18은 짝수
20은 짝수


## # 홀수 표현

In [ ]:
numbers = list(range(1, 21))

for item in numbers :
    
    if item % 2 != 0 :
        
        print(f'{item}은 홀수')

1은 홀수
3은 홀수
5은 홀수
7은 홀수
9은 홀수
11은 홀수
13은 홀수
15은 홀수
17은 홀수
19은 홀수


## # break : 주어진 조건에 따라 진행을 더이상 하지 않고 그 다음 명령문으로 넘어간다.

In [ ]:
# 13이상이면 탈출(break) 또는 계속(continue)

numbers = list(range(1, 21))

for item in numbers :
    
    if item > 12 :
        break
    
    if item % 2 != 0 : 
        
        print(f'{item}은 홀수')

1은 홀수
3은 홀수
5은 홀수
7은 홀수
9은 홀수
11은 홀수


## # cotinue 

In [ ]:
numbers = list(range(1, 21))

for item in numbers :
    
    if item == 15 :        
        continue
    
    if item % 2 != 0 : 
        print(f'{item}은 홀수')

1은 홀수
3은 홀수
5은 홀수
7은 홀수
9은 홀수
11은 홀수
13은 홀수
17은 홀수
19은 홀수


## # end 사용법
  * 다음 출력 내용에 기본으로 적용되는 줄 넘기기 기능 대신에 다른 문자열을 넣을 수 있다.

In [ ]:
# 예시

print("1-1칸","1-2칸","1-3칸")
print("2-1칸","2-2칸","2-3칸")

1-1칸 1-2칸 1-3칸
2-1칸 2-2칸 2-3칸


In [ ]:
print("1-1칸","1-2칸","1-3칸",end = "ㅁ")
print("2-1칸","2-2칸","2-3칸")

1-1칸 1-2칸 1-3칸ㅁ2-1칸 2-2칸 2-3칸


In [ ]:
# 구구단 프로그램
# end를 안 썼을 때 

for i in range(2, 10) : # 2~9단 
    print(f'{i}단 시작')
    print('')
    for j in range(1, 10) : # 1~9를 곱해야 되기 때문
        print(f'{i} x {j} = {i * j:2d}')
    print('')
    print('')
    print('')

2단 시작

2 x 1 =  2
2 x 2 =  4
2 x 3 =  6
2 x 4 =  8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18



3단 시작

3 x 1 =  3
3 x 2 =  6
3 x 3 =  9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27



4단 시작

4 x 1 =  4
4 x 2 =  8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36



5단 시작

5 x 1 =  5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45



6단 시작

6 x 1 =  6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54



7단 시작

7 x 1 =  7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63



8단 시작

8 x 1 =  8
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72



9단 시작

9 x 1 =  9
9 x 2 = 18
9 x 3 = 27
9 x 4 = 36
9 x 5 = 45
9 x 6 = 54
9 x 7 = 63
9 x 8 = 72
9 x 9 = 81





In [ ]:
# 구구단 프로그램
# end를 썼을 떄

for i in range(2, 10) : 
    
    print(f'{i}단 시작')
    print('')
    
    for j in range(1, 10) :
        print(f'{i} x {j} = {i * j:2d}',
              
              end=',   ')
        
    print('')
    print('')
    print('')

2단 시작

2 x 1 =  2,   2 x 2 =  4,   2 x 3 =  6,   2 x 4 =  8,   2 x 5 = 10,   2 x 6 = 12,   2 x 7 = 14,   2 x 8 = 16,   2 x 9 = 18,   


3단 시작

3 x 1 =  3,   3 x 2 =  6,   3 x 3 =  9,   3 x 4 = 12,   3 x 5 = 15,   3 x 6 = 18,   3 x 7 = 21,   3 x 8 = 24,   3 x 9 = 27,   


4단 시작

4 x 1 =  4,   4 x 2 =  8,   4 x 3 = 12,   4 x 4 = 16,   4 x 5 = 20,   4 x 6 = 24,   4 x 7 = 28,   4 x 8 = 32,   4 x 9 = 36,   


5단 시작

5 x 1 =  5,   5 x 2 = 10,   5 x 3 = 15,   5 x 4 = 20,   5 x 5 = 25,   5 x 6 = 30,   5 x 7 = 35,   5 x 8 = 40,   5 x 9 = 45,   


6단 시작

6 x 1 =  6,   6 x 2 = 12,   6 x 3 = 18,   6 x 4 = 24,   6 x 5 = 30,   6 x 6 = 36,   6 x 7 = 42,   6 x 8 = 48,   6 x 9 = 54,   


7단 시작

7 x 1 =  7,   7 x 2 = 14,   7 x 3 = 21,   7 x 4 = 28,   7 x 5 = 35,   7 x 6 = 42,   7 x 7 = 49,   7 x 8 = 56,   7 x 9 = 63,   


8단 시작

8 x 1 =  8,   8 x 2 = 16,   8 x 3 = 24,   8 x 4 = 32,   8 x 5 = 40,   8 x 6 = 48,   8 x 7 = 56,   8 x 8 = 64,   8 x 9 = 72,   


9단 시작

9 x 1 =  9,   9 x 2 = 18,   9 x 3 = 27,  

## # sep :  출력물간 자동으로 들어가는 띄어쓰기 기능 대신에 다른 문자열을 넣을 수 있다.

In [ ]:
print("1-1칸","1-2칸","1-3칸")
print("2-1칸","2-2칸","2-3칸")

1-1칸 1-2칸 1-3칸
2-1칸 2-2칸 2-3칸


In [ ]:
print("1-1칸","1-2칸","1-3칸")
print("2-1칸","2-2칸","2-3칸",sep = "ㅁ")

1-1칸 1-2칸 1-3칸
2-1칸ㅁ2-2칸ㅁ2-3칸


# for 문

In [ ]:
a = [1,2,3,4]

result = [i * 3 for i in a]

print(result)

[3, 6, 9, 12]


In [ ]:
items = [(1,2),(3,4),(5,6)]
# 한개씩 뽑아서 출력하시오
for item in items:
  print( item )
# 값들을 직접 변수로 받아서 데이터를 획득하고 싶다
# 앞에값은 필요없고, 뒤에 값만 필요하다면
for _,b in items:
  print( b )


(1, 2)
(3, 4)
(5, 6)
2
4
6


In [ ]:
# 환율 데이터
exchanges = [
   {
      'code':'USD',
      'buy':1118.11
   },
   {
      'code':'EUR',
      'buy':1318
   }
]
exchanges

[{'buy': 1118.11, 'code': 'USD'}, {'buy': 1318, 'code': 'EUR'}]

In [ ]:
# 데이터를 돌면서, 
# ex) "USD를 구매할때, 한화로 1318원이 필요합니다." 이렇게 출력
for exchange in exchanges:
  # 딕셔너리에서 키를 넣어서 값을 추출 => 인덱싱
  # 인덱싱 => 변수[ 키 ]
  # 문자열이나 코드가 길어져서 내려친다면 \ 표현하여 이어짐을 표시
  print( f"{ exchange[ 'code' ] }를 구매할때, \
  한화로 {exchange[ 'buy' ]}원이 필요합니다." )

USD를 구매할때,   한화로 1118.11원이 필요합니다.
EUR를 구매할때,   한화로 1318원이 필요합니다.


In [ ]:
exchanges[0]

{'buy': 1118.11, 'code': 'USD'}

In [ ]:
# 딕셔너리 데이터를 for으로 사용해 본다면
# 키값이 뽑인다
for dic in exchanges[0]:
  print( dic )

code
buy


In [ ]:
for key in exchanges[0]:
  # 값을 출력하고 싶다면
  print( exchanges[0][ key ] )

USD
1118.11


In [ ]:
tmp = exchanges[0]
for key in tmp:
  # 값을 출력하고 싶다면
  print( tmp[ key ] )

USD
1118.11


In [ ]:
tmp.items()
# [  (키,값), (키,값),... ]

dict_items([('code', 'USD'), ('buy', 1118.11)])

In [ ]:
# 딕셔너리 값을 좀더 심플하게, 키와 값을 추출해 본다
tmp
for k,v in tmp.items():
  print( k, v )


code USD
buy 1118.11


In [ ]:
# 만약 딕셔너리 데이터에서 인덱스를 사용하고 싶다면
# n개의 데이터를 같이 반복문에서 사용할경우
# enumerate() : 내장함수, 인덱스를 부여하여 맴버를 추출

In [ ]:
# 딕셔너리는 순서가 없기 때문에 키가 나오는 순서대로 
# 임의로 인덱스를 붙인다(0, 1, 2, ...)
for index, key in enumerate(tmp):  
  print( index, key, tmp[ key ])
  #print( key, tmp[ key ] )

0 code USD
1 buy 1118.11


## # append 문

In [ ]:
t = []

for i in a :
    
    t.append(i*3)
    
print(t)

[3, 6, 9, 12]


## # def : 함수 선언

In [ ]:
# 더하기 함수 선언

def add(a, b) : 
    res = a + b

    return res

# 함수 사용

print(add(24786, 4324))

29110


  * 매개변수를 지정하는 경우

In [ ]:
def multi(a, b) :
    return a * b

multi(2, 9)

18

  * 매개변수 개수가 가변적일 때

In [ ]:
def plus(*args) :
    
    res = 0

    for i in args :
        res += i

    return res

print(plus(1,2,3))
print(plus(1,2,3,4,5))
print(plus(1,2,3,4,5,6,7,8,9,10))

6
15
55


  * 리턴값이 두 개 이상

In [ ]:
def mul_and_div(x, y) : 
    
    mul = x * y
    
    div = x / y

    return (mul, div)

(res1, res2) = mul_and_div(7,8)

print(res1, res2)

56 0.875


In [ ]:
# 사칙연산

def 사칙연산(x, y) :
    return (x+y, x-y, x*y, x/y)

res1, res2, res3, res4 = 사칙연산(9,5)

print(res1, res2, res3, res4)

14 4 45 1.8


## # while
  * for 와 차이 : while은 조건이 참인 동안에 반복

In [ ]:
hit = 0

while hit < 10 :
    hit = hit + 1

    print(f'나무를 {hit}번 찍습니다.')

나무를 1번 찍습니다.
나무를 2번 찍습니다.
나무를 3번 찍습니다.
나무를 4번 찍습니다.
나무를 5번 찍습니다.
나무를 6번 찍습니다.
나무를 7번 찍습니다.
나무를 8번 찍습니다.
나무를 9번 찍습니다.
나무를 10번 찍습니다.


  * while을 for문으로 바꾸기

In [ ]:
for hit in range(0,100) :
    if hit > 9 :
        break

    print(f'나무를 {hit+1}번 찍습니다.')

나무를 1번 찍습니다.
나무를 2번 찍습니다.
나무를 3번 찍습니다.
나무를 4번 찍습니다.
나무를 5번 찍습니다.
나무를 6번 찍습니다.
나무를 7번 찍습니다.
나무를 8번 찍습니다.
나무를 9번 찍습니다.
나무를 10번 찍습니다.


# input 함수

input 함수가 있어서 이 후 코드가 실행되지 않아서 일단 문자열 처리

val = 0

print('회원정보 프로그램')

while True :

    print(''' 
번호를 입력하세요.

1. 회원입력
2. 회원검색
3. 회원수정
4. 회원삭제
5. 종료
숫자입력 : 
''', end='')
    
    val = int(input()) # 입력

    if val == 1 :
        print('회원정보 입력화면으로 전환')
        
    elif val == 2 :
        print('회원검색 화면으로 전환')
        
    elif val == 3 :
        print('회원수정 화면으로 전환')
        
    elif val == 4 :
        print('회원삭제 화면으로 전환')
        
    elif val == 5 :
        break
        
    else :
        print('1~5 사이 수를 입력하세요')
        continue
        
    print('')

print('회원정보 프로그램 종료')

# 파일 불러오기

## # csv 파일 풀러오기

In [ ]:
import csv

file_name = '/content/drive/MyDrive/Colab Notebooks/python 정리/data_python 정리.ipynb/부산버스정보.csv'

f = open(file_name, mode='r', encoding='utf-8')

reader = csv.reader(f, delimiter=',')  # delimiter 는 구분자. 보통은 쉼표

next(reader) # 헤더(파일의 맨 첫줄)를 없애는 역할

for line in reader :
    print(line)

f.close()

FileNotFoundError: ignored

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

### # 인코딩 오류
* 인코딩 오류가 나오면 csv 파일을 메모장으로 열어서 다른 이름으로 저장할 때 'uft-8'로 저장한다.

# try, except
  * 예외(exception)란 코드를 실행하는 중에 발생한 에러
    - 예) 어떤 숫자를 0으로 나누어서 나타나는 예외를 'ZeroDivisionError'라고 파이썬에서 출력한다.
    - AttributeError, NameError, TypeError 등 다양한 에러들도 모두 예외
  * 그럼 모든 try, except를 적어두는 게 좋지 않나 생각할 수 있지만, 그렇게 되면 이 연산의 성능이 떨어진다.

In [ ]:
def add(a,b) :
    return a + b
def minus(a,b) :
    return a - b
def multi(a,b) :
    return a * b
def divide(a,b) :
    return a / b
print('사칙연산 시작')

a, b = 4, 1

numbers = [3,6,9] # 리스트 생성

try :
    print(f'나누기 결과 : {divide(a,b)}')
    res = int(numbers[3]) * 8
    
except ZeroDivisionError as e:
    print(f'나누기 예외. 추가처리1 {e}')
    
except IndexError as e :
    print(f'인덱스 에외. 추가처리2 {e}')
    
except Exception as e :
    print(f'알 수 없는 예외. 추가처리 5 {e}')
    
finally : # 예외 발생 여부와 상관없이 결과 출력. 반드시 실행해야 하는 close() 명령문에 잘 쓰인다.
    print(f'곱하기기 결과 : {multi(a,b)}')
    print(f'빼기 결과 : {minus(a,b)}')
    print(f'더하기 결과 : {add(a,b)}')

print('사칙연산 종료')

# # 웹 크롤링
  * 값이 '200'이 나오면 페이지를 찾았다는 뜻

In [ ]:
from urllib.request import Request, urlopen

req = Request('http://www.naver.com')

res = urlopen(req)

print(res.status) 

## 사용되는 라이브러리

In [ ]:
from bs4 import BeautifulSoup as bs
from pprint import pprint
import requests

## 수집하고자 하는 사이트 URL을 이용하여 Tag 가지고 오기

In [ ]:
site_url = "https://search.naver.com/search.naver?query=날씨"
html = requests.get(site_url)


# html.text

soup = bs(html.text, "html.parser")
soup

## 태그를 이용해서 데이터 추출하기

In [ ]:
dustdata_one = soup.find("div", {"class" : "scroll_box"})

dustdata_one

In [ ]:
dustdata_all = dustdata_one.findAll("dd", {"class" : "weather_box"})
dustdata_all

In [ ]:
fine_dust_code = dustdata_all[0].find("span", {"class", "blind"})
fine_dust_code

In [ ]:
fine_dust_code_text = dustdata_all[0].find("span", {"class", "blind"}).text

fine_dust_code_text

In [ ]:
for i in range(0, len(dustdata_all) -1 ) :
    fine_dust_code_text = dustdata_all[i].find("span", {"class", "blind"}).text
    print(fine_dust_code_text)

# StudyPython/day5/ : 파이썬에서 oracle을 사용하는 방법
  * 폴더 정리는 나중에 책으로 한 번 더

# # class(클래스)

## ## 뜻
  * 클래스는 class에 클래스 이름을 지정하고 :(콜론)을 붙인 뒤 
    - 클래스 이름을 짓는 방법은 변수와 같습니다. 보통 파이썬에서는 클래스의 이름은 대문자로 시작합니다. 
  * 다음 줄부터 def로 메서드를 작성하면 됩니다.
    - 메서드 : 클래스 안에 들어있는 함수
      + 메서드 작성 방법은 함수와 같으며 코드는 반드시 들여쓰기를 해야 합니다(들여쓰기 규칙은 if, for, while과 같습니다).
      + 특히 메서드의 첫 번째 매개변수는 반드시 self를 지정해야 합니다.

In [ ]:
class Person:
     def greeting(self):
         print('Hello')

  *  클래스에 ()(괄호)를 붙인 뒤 변수에 할당
    - 클래스는 특정 개념을 표현만 할뿐 사용을 하려면 인스턴스를 생성해야 합니다.

In [ ]:
# Person으로 변수 james를 만들었는데 이 james가 Person의 인스턴스(instance)입니다. 

james = Person()

  * 메서드는 클래스가 아니라 인스턴스를 통해 호출

In [ ]:
#  다음과 같이 인스턴스 뒤에 .(점)을 붙이고 메서드를 호출

james.greeting()

  * int, list, dict 등도 사실 클래스

In [ ]:
# int 클래스에 10을 넣어서 인스턴스 a를 만들었습니다.

a = int(10)

a

## ## 개요
  * s/w 개발 방식
    - 절차적 프로그래밍
      + C/C++, python, javascript ...
        * 코드의 재사용성을 구현하기 힘들다.
    - 함수 지향적 프로그래밍
      + 절차적(타입, 자료구조, 조건/제어/반복문) + 함수
      + C/C++, python, javascript ...
        * 코드의 재사용성 가능, 생산성 증가, 구조적 개발
        * 최근 다시 유행하고 있다(리엑트)
    - 객채 지향적 프로그래밍
      + C++, java, python, javascript, kotlin, swift, scalar
      + 절차적 + 함수 + calss 개념
        * 객체 지향 프로그래밍
          - 상속성, 다형성, 은닉성 3가지 특성이 있어야 한다.
          - GUI 프로그램(윈도우 프로그램) 
            + [pyQT5](https://wikidocs.net/21849)
            + [exe](https://www.google.com/search?q=python+exe&newwindow=1&rlz=1C1CHBD_koKR988KR988&sxsrf=APq-WBs0Vo_G56ETMaye4cuX_MVLxyS0AQ%3A1650933137313&ei=kT1nYv7gEoqG-AaMuJfwBQ&ved=0ahUKEwi-7cmZvbD3AhUKA94KHQzcBV4Q4dUDCA4&uact=5&oq=python+exe&gs_lcp=Cgdnd3Mtd2l6EAMyCggAEIAEEIcCEBQyBQgAEIAEMgsIABCABBCxAxCDATIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQ6BAgjECc6BAgAEEM6CggAELEDEIMBEENKBAhBGABKBAhGGABQAFjCDGCjDmgAcAF4AIABqQGIAeMIkgEDMi44mAEAoAEBwAEB&sclient=gws-wiz)

## ## 개념
  * entity(개체)
    - 이 세상에 존재하는 모든 개념(무형), 실존하는 것(유형)
    - 이런 entity를 컴퓨터 사이언스, 프로그램밍 세상에 entity를 표현하기 위해서는 도구가 필요 => class라는 문법(표현도구)을 가지고 구현
  * class
    - 문법이 존재, 엔티티를 표현하는 도구
    - 클래스를 작성 -> 실행 -> 클래스 생성자를 호출
    - 클래스의 모습을 본딴 형태로 메모리에 뭔가가 상주하게 된다. -> 객체(object)
    - 클래스의 인스턴스를 객체라고 부른다.
      + 여러 개 만들 수 있다.
    - 객체의 청사진은 클래스라고 부른다.
  * object
    - 프로그램이 작동하면 메모리상에 존재
    - 메모리 상에 존재하니까, 주소가 존재 (0x7123412lk3n)
    - 특정 변수가 그 객체를 받아주면 이제부터 그 변수를 xxx 객체라고 부른다.
      + 정확하게는 특정 변수가 주소 0x7123412lk3n를 가진 객체를 가르킨다.(특정 객체를 가리키는 주소를 가진다.)

## ## Object
  * 모든 클래스(이미 만들어져 있거나, 내가 만들거나)의 부모 클래스이다.

## ## 문법

In [ ]:
# 클레스 정의
class Person :
  pass

# 클래스 사용 -> 객체 생성
# 반복문 안에서는 사용시 책임지고 해제(del)한다.
p = Person()

In [ ]:
# p를 통해서 Person 객체를 접근할 수 있다.
p

In [ ]:
# 해제
del p

In [ ]:
p

## ## 클레스 구성원
  * 생성자
  * 멤버
    - 변수
      - 접근제어를 표현할 수 있는데 차후 언급
    - 함수
  * 소멸자
  * 기타 _로 시작하는 사전 정의된 함수들 
  * 정적함수

In [ ]:
# 멤버 -> 클래스 소속이다 -> 객체명.맴버변수 or 객체명.멤버함수
# Person 클래스 내부에서 자기 자신을 표현할 때 => self or(타 언어는 this)

# 부모 클래스를 명시적으로 표현하지 않아도 이미 Object(모든 클레스의 슈퍼 클레스)를 상속하고 있다.
# class Person(Object) :

class Person :
  # 생성자(생략 가능함 -> 부모 생성자가 있으니까 그것을 그대로 사용)
  # 멤버 변수
  p = 0.2
  # 멤버 함수
  def getP(self) : 
    return self.p

per = Person()

In [ ]:
# 객체명.맴버변수
per.p

In [ ]:
# 객체명.멤버함수
per.getP()

## ## 상속
  * 부모 클레스로부터 모든 유산을 받아서 자식 클레스는 사용 가능
  * 부모로 부터 받은 유산을 재정의해서 사용 가능
  * 자식 클레스는 별도로 새로운 기능을 만들어서 추가할 수 있다.
  * Xman > Person > Object
    - Xman은 Object이다(is a)
    - Object는 자식으로 Xman을 가진다( has a )

In [ ]:
class XMan(Person) :
  def attack(self) : 
    print('하늘을 나는 능력을 추가했다.')

x = XMan()

In [ ]:
x.p, x.getP(), x.attack()

## # 빈 클래스 만들기
  * 내용이 없는 빈 클래스를 만들 때는 코드 부분에 pass를 넣어줍니다.

In [ ]:
class Person:
    pass

## # 클래스 예시
  * 책을 보면서 한 번 따라해보기
  * 아직 충분히 이해가 되지 않음

In [ ]:
class Person :
    name = '무명이' 
    age = 0
    height = 0
    gender = ''
    feetsize = 250
    bloodtype = ''

    
    # 생성자

    def __init__(self, name, age, height, gender) -> None : # 초기화
        self.name = name
        self.age = age
        self.height = height
        self.gender = gender
        print('Person이 생성되었습니다.')

    def 소개한다(self) -> None : 
        greeting = f'''안녕하세요. 저는 {self.name}입니다.
        {self.gender} 구요. {self.age}
        '''
        print(greeting)

    def 먹는다(self, food) :
        print(f'{self.name}(이)가 {food}를 먹는다.')

    def 일한다(self, drink) :
        print(f'{self.name}(이)가 {drink}를 마시면서 일한다.')

if __name__  == '__main__' :

    jgy = Person('정기영', 34, 180, 'male') # == __init__(self, name, age):
    # jgy.name = '정기영'
    # jgy.age = 34
    # jgy.height = 180
    # jgy.gender = 'male'
    jgy.feetsize = 275
    jgy.bloodtype = 'RH+ A'
    
    jgy.소개한다()
    jgy.먹는다('본죽')
    jgy.일한다('핫식스')

### ### [python의 self와 __init__의 이해](https://engineer-mole.tistory.com/190) 

In [ ]:
class Car :
    차량번호 = '22나 4444'
    # 기본값 : 따로 값을 넣지 않으면 차량번호는 22나 4444
    __제조사 = '현대'
    """ 
    # 앞에다가 __(언더바 두개)를 '프라이빗(private)'이라고 부르고 class 밖에서는 값으로 접근이 불가능하도록 하는 기능이다. 
      * 다만 Python은 유연한 언어라서 private 으로 만들어도 접근이 가능하다.
    """

    색상 = '흰색'
    연료 = '가솔린'
    출고년도 = 2018

    def __init__(self, 차량번호, 색상) -> None :
        self.차량번호 = 차량번호
        self.색상 = 색상

    def __str__(self) -> str:
        return f'제 차는 {self.출고년도}년도에 만들어진 {self.연료} 차량입니다.'

    def 전진한다(self, level) :
        print(f'{self.색상}차가 {level}단 앞으로 달린다.')

# 그 외 기초 함수

## ## reshape

In [ ]:
array1 = np.arange(10)
print('array1:\n', array1)

array1:
 [0 1 2 3 4 5 6 7 8 9]


In [ ]:
array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


### ### reshape(-1, -1)의 의미
  * 행렬 중 고정된 수가 있다면 그 수를 제외하고 만들 수 있는 행렬로 자동 완성

In [ ]:
array1 = np.arange(10)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)

array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)

array2 shape: (2, 5)
array3 shape: (5, 2)


In [ ]:
# 삭제
# 파이썬 표현 내에서 특정 변수를 해제하는 방법 : del
del c[0]
c

## # 인코딩
  * 영어 : ascii
  * 한글 : cp949
  * 중국어 포함 모든 언어 : utf-8

## ## 레이블 인코딩
  * LabelEncoder를 객체로 생성한 후 ,
  * fit( ) 과 transform( ) 으로 label 인코딩 수행. 

In [ ]:
from sklearn.preprocessing import LabelEncoder

items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

encoder = LabelEncoder()

encoder.fit(items)

labels = encoder.transform(items)

print('인코딩 변환값:',labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


### ### 원래 레이블

In [ ]:
print('인코딩 클래스:',encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [ ]:
print('디코딩 원본 값:',encoder.inverse_transform([4, 5, 2, 0, 1, 1, 3, 3]))

디코딩 원본 값: ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


## ## 원핫 인코딩
  * one-hot encoding

|상품분류|가격|
|--|--|
|TV|1000|
|냉장고|500|
|컴퓨터|800|

  * 상품분류를 숫자로 변환

|상품분류|가격|
|--|--|
|1|1000|
|2|500|
|3|800|

  * 몇몇 알고리즘에서는 예측 성능이 떨어지는 경우가 있다.
    - 왜냐하면 TV가 1이고 냉장고가 2이면 냉장고에게 가중치를 부여하는 알고리즘도 있기 때문이다.
  * 이를 방지하기 위해서, 행 형태로 돼 있는 피처의 고유 값을 열 형태로 차원을 변환한 뒤, 고유 값에 해당하는 칼럼에만 1을 표시하고 나머지는 0을 표시

|상품분류|
|--|
|TV|
|냉장고|
|컴퓨터|

을

|상품분류-TV|상품분류-냉장고|상품분류-컴퓨터
|--|--|--|
|1|0|0|
|0|1|0|
|0|0|1





In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

# 2차원 ndarray로 변환합니다. 
items = np.array(items).reshape(-1, 1)

# 원-핫 인코딩을 적용합니다. 
oh_encoder = OneHotEncoder()
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)

# OneHotEncoder로 변환한 결과는 희소행렬이므로 toarray()를 이용해 밀집 행렬로 변환. 
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


### ### 판다스 버전

In [ ]:
import pandas as pd

df = pd.DataFrame({'item':['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서'] })
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

## # Escape character 탈출문자(특수문자)
  * \ 혹은 역슬래쉬
  * 파이썬에서 자동으로 식별자로 인식하는 ( 예) ", ' 등) 걸 방지하는 식별자

In [ ]:
print('Life is short.\nYou need Python.')
print()

print('Life is short.\rYou need Python.')
print()

print('Life is short.\r\nYou \tneed \'Python.\'')
print()

print('Life is short.\r\nYou \t\bneed \'Python.\'')
print()

print('Life is \"short\".\r\nYou \t\bneed \'Python.\'')
print()

## ## random 함수

In [ ]:
import random 

numbers = list(range(1, 46))

lottery = [] 

for i in range(6) :
    lottery.append(random.choice(numbers))

print(lottery)

## ## random()
  * 0 이상 1 미만의 숫자 중에서 아무 숫자나 하나 뽑아서 돌려주는 일을 한답니다.

In [ ]:
m = [random.random() for n in range(1000)]
print(m)

# 공공데이터 Open API 데이터 읽어오기

In [ ]:
import pandas
from bs4 import BeautifulSoup
import requests
from openpyxl.workbook import Workbook

In [ ]:
# api key 입력

apikey='2iBxaKFKnzeyq04AkTe7ZCYjXgKOO6sXWOegK0YOWsgfPk%2FyFKrzqSaEiKFNMSUDX9qffhdPG0ajf0ydWGVzFQ%3D%3D'

# 약국정보서비스 URL
api = "http://apis.data.go.kr/B551182/pharmacyInfoService/getParmacyBasisList?serviceKey=2iBxaKFKnzeyq04AkTe7ZCYjXgKOO6sXWOegK0YOWsgfPk%2FyFKrzqSaEiKFNMSUDX9qffhdPG0ajf0ydWGVzFQ%3D%3D&pageNo=1&numOfRows=10&sidoCd=110000&sgguCd=110019&emdongNm=%EC%8B%A0%EB%82%B4%EB%8F%99&yadmNm=%EC%98%A8%EB%88%84%EB%A6%AC%EA%B1%B4%EA%B0%95&type=json&APPID={key}"

# 약국정보 컬럼(제목) 정의
list_drugs = ["병원명", "종목코드명", "시도명", "주소", "전화번호"]

In [ ]:
# API 정보 가지고 오기
for list_drug in list_drugs : 
    url = api.format(list_drugs = list_drug,
                    key = apikey)
    
    req = requests.get(url)
    re = req.text
    soup = BeautifulSoup(re, "html.parser")
    # print(soup)
    
    yadmnm = soup.find_all("yadmnm")
    sggucdnm = soup.find_all("sggucdnm")
    sidocdnm = soup.find_all("sidocdnm")
    addr = soup.find_all("addr")
    telno = soup.find_all("telno")
    
    print("병원명 : ", yadmnm)
    print("종목코드명 : ", sggucdnm)
    print("시도명 : ", sidocdnm)
    print("주소 : ", addr)
    print("전화번호 : ", telno)
    print("==========================")

# ㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁ

# # 데이터 전처리 과정 실습
  * 관광객 데이터

## ## 데이터 불러오기

In [ ]:
import pandas as pd

# 파일 경로 지정
file_path = "/content/drive/MyDrive/Colab Notebooks/data_python 정리.ipynb/files_관광데이터/kto_201901.xlsx"

# 파일을 읽어 들여서 DataFrame 형태로 읽어드리기
kto_201901 = pd.read_excel(file_path,
                           header=1, # 컬럼명 위치. 기본값은 0.
                          skipfooter = 4, # 제일 밑 행에서 부터 삭제할 행 번호
                           usecols = "A:G" # 사용할 열 선택
                          )
kto_201901

## ## 결측치 유무 확인

In [ ]:
kto_201901.info()

## ## 기초통계 확인
  * 의심스러운 값 확인
    - 이 경우 최소값에 0이 보인다.

In [ ]:
kto_201901.describe()